// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiuzgOcvwOCji6EJJdKBdMJGhWNxd2zgs',
    appId: '1:28440160509:web:9efad0eb68c6190d857694',
    messagingSenderId: '28440160509',
    projectId: 'merapartners-35393',
    authDomain: 'merapartners-35393.firebaseapp.com',
    storageBucket: 'merapartners-35393.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPQOxfwkXM-y_oBZifWbOnoifOBK-75jc',
    appId: '1:28440160509:android:b0ec850c56fe4dff857694',
    messagingSenderId: '28440160509',
    projectId: 'merapartners-35393',
    storageBucket: 'merapartners-35393.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcra8Dw_HGUj9zhcI6uRiHSCvfia8lqM4',
    appId: '1:28440160509:ios:6810b9dcd29299a2857694',
    messagingSenderId: '28440160509',
    projectId: 'merapartners-35393',
    storageBucket: 'merapartners-35393.appspot.com',
    iosBundleId: 'com.meracars.meraPartners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcra8Dw_HGUj9zhcI6uRiHSCvfia8lqM4',
    appId: '1:28440160509:ios:6810b9dcd29299a2857694',
    messagingSenderId: '28440160509',
    projectId: 'merapartners-35393',
    storageBucket: 'merapartners-35393.appspot.com',
    iosBundleId: 'com.meracars.meraPartners',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiuzgOcvwOCji6EJJdKBdMJGhWNxd2zgs',
    appId: '1:28440160509:web:19eaeb80dc77bc8f857694',
    messagingSenderId: '28440160509',
    projectId: 'merapartners-35393',
    authDomain: 'merapartners-35393.firebaseapp.com',
    storageBucket: 'merapartners-35393.appspot.com',
  );
}
